
SELECT
    EXPERIENCE AS EXP
    , COUNT(CASE WHEN ( coalesce(SQL, 100)+ coalesce(ALGO, 100)+ coalesce(BUG_FIXING,100)  = 300) THEN 1 END)     AS MAX
    , COUNT(*) AS COUNT
FROM ASSESSMENTS
GROUP BY EXPERIENCE
ORDER BY EXPERIENCE DESC
;